kind: pipeline
name: combustion_theme_amd64
type: docker

platform:
  os: linux
  arch: amd64

node:
  type: hosted-amd64

steps:
  - name: build
    image: gcr.io/kaniko-project/executor:v1.12.0-debug
    environment:
      HARBOR_USERNAME:
        from_secret: registry_username
      HARBOR_PASSWORD:
        from_secret: registry_password
    commands:
      -  echo "{\"auths\":{\"registry.adamkoro.com\":{\"auth\":\"$(printf "%s:%s" "$HARBOR_USERNAME" "$HARBOR_PASSWORD" | base64 )\"}}}" > /kaniko/.docker/config.json
      - /kaniko/executor
        --context "."
        --dockerfile "./Dockerfile"
        --destination "registry.adamkoro.com/transmission/transmission:4.0.3-latest"
        --destination "registry.adamkoro.comtransmission/transmission:4.0.3-combustion"
        --build-arg opts="CGO_ENABLED=0 GOARCH=amd64"
