kind: pipeline
name: build
type: kubernetes

steps:
  - name: build-amd64
    image: gcr.io/kaniko-project/executor:v1.12.0-debug
    commands:
      - /kaniko/executor
        --context "."
        --dockerfile "./Dockerfile"
        --destination "harbor.adamkoro.com/transmission/transmission:latest"
        --destination "harbor.adamkoro.com/transmission/transmission:4.0.3-combustion"
