kind: pipeline
name: build
type: kubernetes

steps:
  - name: build-amd64
    image: gcr.io/kaniko-project/executor:v1.12.0-debug
    environment:
      HARBOR_USERNAME:
        from_secret: harbor_username
      HARBOR_PASSWORD:
        from_secret: harbor_password
    commands:
      -  echo "{\"auths\":{\"harbor.adamkoro.com\":{\"auth\":\"$(printf "%s:%s" "${HARBOR_USERNAME}" "${HARBOR_PASSWORD}" | base64 )\"}}}" > /kaniko/.docker/config.json
      - /kaniko/executor
        --context "."
        --dockerfile "./Dockerfile"
        --destination "harbor.adamkoro.com/transmission/transmission:4.0.3-latest"
        --destination "harbor.adamkoro.com/transmission/transmission:4.0.3-combustion"
