kind: pipeline
name: transmission
type: kubernetes

steps:
  - name: build
    image: plugins/kaniko
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      registry: harbor.adamkoro.com
      repo: harbor.adamkoro.com/transmission/transmission
      tags: 
        - latest
        - 4.0.3-combustion