kind: pipeline
name: build
type: kubernetes

steps:
  - name: multiarch
    image: gcr.io/kaniko-project/executor:v1.11.0
    commands:
      - /kaniko/executor
        --context "."
        --dockerfile "./Dockerfile"
        --destination "harbor.adamkoro.com/transmission/transmission:${DRONE_COMMIT_SHA}"
