ARG TRANSMISSION_VERSION

FROM registry.suse.com/bci/bci-base:15.5 as builder
WORKDIR /transmission-web
RUN zypper ref && zypper -n in unzip
RUN curl -LO https://github.com/Secretmapper/combustion/archive/release.zip && \
    unzip release.zip && \
    rm -rf release.zip

FROM docker.io/linuxserver/transmission:${TRANSMISSION_VERSION}
ENV TRANSMISSION_WEB_HOME=/usr/share/transmission/custom-web
COPY --from=builder /transmission-web/combustion-release /usr/share/transmission/custom-web
